### ISSUE TITLE
动态更新某个cell的高度时会导致cell显示错乱

### ISSUE THREAD

**Issue by Liaoworking** [OlderChicken/CustomLayout#2]
我们项目的需求是在图片加载完成后根据图片的高度去动态调整cell高度， 这个时候再去reloadItems(at: IndexPath) 就会cell显示错乱。

**Comment by nobodyJee** [comment]
@Liaoworking 你好，不知道你说的错乱是什么样的，建议图片下载完成之后先异步计算每一个图片的高度，然后再更新 UI，一定要保证图片的高度是正确的

**Comment by Liaoworking** [comment]
我用同步reload会有问题，改成了异步reload就好了。
